### ISSUE TITLE
Look for and use a React Native component appropriate for entering passwords

### ISSUE THREAD

**Issue by pranav-kulshreshtha** [varshney-prince/Chat#5]

**Comment by varshney-prince** [comment]
Done

**Comment by pranav-kulshreshtha** [comment]
Are you working on the remaining ones? What's the progress?

**Comment by pranav-kulshreshtha** [comment]
public static int fun(int[][] matrix){
        Arrays.sort(matrix, (a,c) -> Math.min(a[0],a[2]) -
Math.min(c[0],c[2]));
        int current = 0;
        int count=0;
        for(int i=1;i<matrix.length;i++){

if(Math.max(matrix[current][1],matrix[current][3])<Math.min(matrix[i][0],matrix[i][2])
){
                current = i;
            }
            else count++;
        }
        return count;
    }
